Mara/Areas/admin/Controllers/SlideController.cs
using BusinessLayer.Repositories;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Mara.Areas.admin.Controllers
{

    [Area("admin"), Authorize]
    public class SlideController : Controller
    {
        IRepository<Slide> _slideRepository;

        public SlideController(IRepository<Slide> slideRepository)
        {
            _slideRepository = slideRepository;
        }




        [Route("SlaytYönetimi")]
        public IActionResult Index()
        {
            var slides = _slideRepository.GetAll().OrderBy(a => a.ID);

            return View(slides);
        }




        [Route("YeniSlaytEkle")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("YeniSlaytEkle")]
        public async Task<IActionResult> Create(Slide model)
        {
            //create action'nun view kısmında olan form içerisinden gönderilen bir form files var ise bu bloğa gir (resim vb.)
            if (Request.Form.Files.Any())
            {
                //eğer aşağıdaki blok içerisinde yazılmış olan konumda bir "slideimages" klasörü yok ise..
                if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "slideimages")))
                {
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "slideimages")); //Burada o konumda "slideimages" adında yeni bir klasör oluştur.
                }

                //dosya adı kayıt edilirken aynı isimde olmamasını sağlamak için aşağıda, repo üzerinden bütün slideların sayısını string olarak çektik ve her yeni eklemede +1 eklenmesini sağladık, bu şekilde dosya isimleri aynı olmayacak.
                string dosyaAdi = (_slideRepository.GetAll().Count() + 1) + Request.Form.Files["SlidePicture"].FileName;

                //yukarıdan gelen dosya adını belirtilen directory de kayıt et 
                using (FileStream stream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "slideimages", dosyaAdi), FileMode.Create))
                {
                    await Request.Form.Files["SlidePicture"].CopyToAsync(stream); //<---- formdan gelen dosyayı kayıt et
                }
                
                model.SlidePicture = "/slideimages/" + dosyaAdi; // <----- Veri tabanında gözükeceği ad düzeni..

            }

            await _slideRepository.AddAsync(model);
            return RedirectToAction("Index");
        }




        [HttpGet]
        [Route("SlaytGüncelle")]
        public async Task<IActionResult> Update(int id)
        {
            var getSlideToUpdate = await _slideRepository.GetByAsync(a => a.ID == id);

            return View(getSlideToUpdate);
        }

        [HttpPost]
        [Route("SlaytGüncelle")]
        public async Task<IActionResult> Update(Slide model)
        {
            
            if (Request.Form.Files.Any())
            {            
                if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "slideimages")))
                {
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "slideimages")); //Burada o konumda "slideimages" adında yeni bir klasör oluştur.
                }
                
                string dosyaAdi = (_slideRepository.GetAll().Count() + 1) + Request.Form.Files["SlidePicture"].FileName;

                using (FileStream stream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "slideimages", dosyaAdi), FileMode.Create))
                {
                    await Request.Form.Files["SlidePicture"].CopyToAsync(stream);
                }

                model.SlidePicture = "/slideimages/" + dosyaAdi;
            }

            await _slideRepository.UpdateAsync(model);

            return RedirectToAction("Index");
        }




        [Route("SlaytSil")]
        public async Task<IActionResult> Delete(int id)
        {
            var slide = await _slideRepository.GetByAsync(x => x.ID == id);

            await _slideRepository.DeleteAsync(slide);

            return RedirectToAction("Index");
        }
    }
}

Mara/Areas/admin/Views/Slide/Create.cshtml
@model Slide

<main class="page-content">
    <h6 class="mb-0 text-center text-uppercase">Yeni Slayt Ekle</h6>
    <br />
    <div class="container mt-5">
        <div class="row justify-content-center text-center">
            <div class="col-4">
                <form asp-controller="Slide" asp-action="Create" method="post" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label asp-for="SlideTitle" class="form-label fw-bold"></label>
                        <input asp-for="SlideTitle" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlideTitle"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlideDescription" class="form-label fw-bold"></label>
                        <input asp-for="SlideDescription" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlideDescription"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlidePrice" class="form-label fw-bold"></label>
                        <input asp-for="SlidePrice" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlidePrice"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlidePicture" class="form-label fw-bold"></label>
                        <input asp-for="SlidePicture" type="file" accept="image/*" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlidePicture"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlideLink" class="form-label fw-bold"></label>
                        <input asp-for="SlideLink" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlideLink"></span>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary">Ekle</button>
                        <a asp-controller="Slide" asp-action="Index" class="btn btn-danger">İptal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

Mara/Areas/admin/Views/Slide/Index.cshtml
@model IEnumerable<Slide>


<main class="page-content">

    <h6 class="mb-0 text-center text-uppercase">Slayt Yönetimi</h6>
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center gap-2 justify-content-end mb-3">
                <button class="btn btn-sm btn-light px-2"><i class="bi bi-box-arrow-right me-2"></i>Export</button>
                <a asp-controller="Slide" asp-action="Create" class="btn btn-sm btn-primary px-2"><i class="bi bi-plus-lg me-2"></i>Yeni Ekle</a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-xxl-8">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-borderless mb-0">
                            <thead>
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Slayt Başlığı</th>
                                    <th scope="col">Slayt Açıklaması</th>
                                    <th scope="col">Slayt Fiyatı</th>
                                    <th scope="col">Slayt Fotoğrafı</th>
                                    <th scope="col">Slayt Bağlantısı</th>
                                    <th scope="col">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (Slide slide in Model)
                                {
                                    <tr class="text-center align-middle">
                                        <th scope="row">@slide.ID</th>
                                        <td>@slide.SlideTitle</td>
                                        <td>@slide.SlideDescription</td>
                                        <td>@slide.SlidePrice</td>
                                        <td><img src="@slide.SlidePicture" height="100" style="border-radius:10px;" /></td>
                                        <td>@slide.SlideLink</td>
                                        <td>
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                                <a asp-controller="Slide" asp-action="Update" asp-route-id="@slide.ID" title="Slaytyı Güncelle" class="btn btn-warning">
                                                    <span class="material-symbols-outlined me-0">refresh</span>
                                                </a>
                                                <a asp-controller="Slide" asp-action="Delete" asp-route-id="@slide.ID" title="Slaytyı Sil" class="btn btn-danger">
                                                    <span class="material-symbols-outlined me-0">delete</span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!--end main content-->

Mara/Areas/admin/Views/Slide/Update.cshtml
@model Slide

<main class="page-content">
    <h6 class="mb-0 text-center text-uppercase">Slayt Düzenle</h6>
    <br />
    <div class="container mt-5">
        <div class="row justify-content-center text-center">
            <div class="col-4">
                <form asp-controller="Slide" asp-action="Update" method="post" enctype="multipart/form-data">
                    <input asp-for="ID" type="hidden" />
                    <input asp-for="SlidePicture" type="hidden" />
                    <div class="mb-3">
                        <label asp-for="SlideTitle" class="form-label fw-bold"></label>
                        <input asp-for="SlideTitle" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlideTitle"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlideDescription" class="form-label fw-bold"></label>
                        <input asp-for="SlideDescription" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlideDescription"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlidePrice" class="form-label fw-bold"></label>
                        <input asp-for="SlidePrice" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlidePrice"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlidePicture" class="form-label fw-bold"></label>
                        <input asp-for="SlidePicture" type="file" accept="image/*" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlidePicture"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="SlideLink" class="form-label fw-bold"></label>
                        <input asp-for="SlideLink" class="form-control">
                        <span class="text-danger fw-bold" asp-validation-for="SlideLink"></span>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary">Güncelle</button>
                        <a asp-controller="Slide" asp-action="Index" class="btn btn-danger">İptal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>