Mara/ViewComponents/HeaderSecondViewComponent.cs
using BusinessLayer.Repositories;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Mara.ViewComponents
{
    public class HeaderSecondViewComponent : ViewComponent
    {
        IRepository<Category> _categoryRepository;

        public HeaderSecondViewComponent(IRepository<Category> categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }


        public IViewComponentResult Invoke()
        {
            var categories = _categoryRepository.GetAll().Include(x=>x.SubCategories).OrderBy(x=>x.ID);

            return View(categories);
        }
    }
}

Mara/ViewComponents/HeaderViewComponent.cs
using BusinessLayer.Repositories;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Mara.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        IRepository<Category> _categoryRepository;

        public HeaderViewComponent(IRepository<Category> categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _categoryRepository.GetAll().Include(a=>a.SubCategories).OrderBy(a=>a.ID);

            return View(categories);
        }
    }
}

Mara/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ozan">
    <title>ECOSHOP - Multipurpose eCommerce HTML5 Template</title>

    <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="/rs-plugin/css/settings.css" media="screen" />

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/css/ionicons.min.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/responsive.css" rel="stylesheet">

    <!-- Online Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>


</head>
<body>

    <!-- LOADER -->
    <div id="loader">
        <div class="position-center-center">
            <div class="ldr"></div>
        </div>
    </div>

    <!-- Wrap -->
    <div id="wrap">

        @await Component.InvokeAsync("Header");

        <!-- MAIN  CONTENT -->

        @RenderBody()

        <!--======= FOOTER =========-->
        <footer>
            <div class="container">

                <!-- ABOUT Location -->
                <div class="col-md-3">
                    <div class="about-footer">
                        <img class="margin-bottom-30" src="images/logo-foot.png" alt="">
                        <p>
                            <i class="icon-pointer"></i> Street No. 12, Newyork 12, <br>
                            MD - 123, USA.
                        </p>
                        <p><i class="icon-call-end"></i> 1.800.123.456789</p>
                        <p><i class="icon-envelope"></i> info@ecoshop.com</p>
                    </div>
                </div>

                <!-- HELPFUL LINKS -->
                <div class="col-md-3">
                    <h6>HELPFUL LINKS</h6>
                    <ul class="link">
                        <li><a href="#."> Products</a></li>
                        <li><a href="#."> Find a Store</a></li>
                        <li><a href="#."> Features</a></li>
                        <li><a href="#."> Privacy Policy</a></li>
                        <li><a href="#."> Blog</a></li>
                        <li><a href="#."> Press Kit </a></li>
                    </ul>
                </div>

                <!-- SHOP -->
                <div class="col-md-3">
                    <h6>SHOP</h6>
                    <ul class="link">
                        <li><a href="#."> About Us</a></li>
                        <li><a href="#."> Career</a></li>
                        <li><a href="#."> Shipping Methods</a></li>
                        <li><a href="#."> Contact</a></li>
                        <li><a href="#."> Support</a></li>
                        <li><a href="#."> Retailer</a></li>
                    </ul>
                </div>

                <!-- MY ACCOUNT -->
                <div class="col-md-3">
                    <h6>MY ACCOUNT</h6>
                    <ul class="link">
                        <li><a href="#."> Login</a></li>
                        <li><a href="#."> My Account</a></li>
                        <li><a href="#."> My Cart</a></li>
                        <li><a href="#."> Wishlist</a></li>
                        <li><a href="#."> Checkout</a></li>
                    </ul>
                </div>

                <!-- Rights -->
                <div class="rights">
                    <p>©  @DateTime.UtcNow.Year Kikea All right reserved.</p>
                    <div class="scroll"> <a href="#wrap" class="go-up"><i class="lnr lnr-arrow-up"></i></a> </div>
                </div>
            </div>
        </footer>
    </div>

    <!-- JavaScripts -->
    <script src="/js/modernizr.js"></script>
    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/own-menu.js"></script>
    <script src="/js/jquery.lighter.js"></script>
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/main.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="/rs-plugin/js/jquery.tp.t.min.js"></script>
    <script type="text/javascript" src="/rs-plugin/js/jquery.tp.min.js"></script>
</body>
</html>

Mara/Views/Shared/_Layout_2.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ozan">
    <title>ECOSHOP - Multipurpose eCommerce HTML5 Template</title>

    <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="/rs-plugin/css/settings.css" media="screen" />

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/css/ionicons.min.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/responsive.css" rel="stylesheet">

    <!-- Online Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>


</head>
<body>

    <!-- LOADER -->
    <div id="loader">
        <div class="position-center-center">
            <div class="ldr"></div>
        </div>
    </div>

    <!-- Wrap -->
    <div id="wrap">

        @await Component.InvokeAsync("HeaderSecond");

        @RenderBody()

        <!--======= FOOTER =========-->
        <footer>
            <div class="container">

                <!-- ABOUT Location -->
                <div class="col-md-3">
                    <div class="about-footer">
                        <img class="margin-bottom-30" src="images/logo-foot.png" alt="">
                        <p>
                            <i class="icon-pointer"></i> Street No. 12, Newyork 12, <br>
                            MD - 123, USA.
                        </p>
                        <p><i class="icon-call-end"></i> 1.800.123.456789</p>
                        <p><i class="icon-envelope"></i> info@ecoshop.com</p>
                    </div>
                </div>

                <!-- HELPFUL LINKS -->
                <div class="col-md-3">
                    <h6>HELPFUL LINKS</h6>
                    <ul class="link">
                        <li><a href="#."> Products</a></li>
                        <li><a href="#."> Find a Store</a></li>
                        <li><a href="#."> Features</a></li>
                        <li><a href="#."> Privacy Policy</a></li>
                        <li><a href="#."> Blog</a></li>
                        <li><a href="#."> Press Kit </a></li>
                    </ul>
                </div>

                <!-- SHOP -->
                <div class="col-md-3">
                    <h6>SHOP</h6>
                    <ul class="link">
                        <li><a href="#."> About Us</a></li>
                        <li><a href="#."> Career</a></li>
                        <li><a href="#."> Shipping Methods</a></li>
                        <li><a href="#."> Contact</a></li>
                        <li><a href="#."> Support</a></li>
                        <li><a href="#."> Retailer</a></li>
                    </ul>
                </div>

                <!-- MY ACCOUNT -->
                <div class="col-md-3">
                    <h6>MY ACCOUNT</h6>
                    <ul class="link">
                        <li><a href="#."> Login</a></li>
                        <li><a href="#."> My Account</a></li>
                        <li><a href="#."> My Cart</a></li>
                        <li><a href="#."> Wishlist</a></li>
                        <li><a href="#."> Checkout</a></li>
                    </ul>
                </div>

                <!-- Rights -->

                <div class="rights">
                    <p>©  @DateTime.UtcNow.Year Kikea All right reserved. </p>
                    <div class="scroll"> <a href="#wrap" class="go-up"><i class="lnr lnr-arrow-up"></i></a> </div>
                </div>
            </div>
        </footer>

    </div>

    <!-- JavaScripts -->
    <script src="/js/modernizr.js"></script>
    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/own-menu.js"></script>
    <script src="/js/jquery.lighter.js"></script>
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/main.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="/rs-plugin/js/jquery.tp.t.min.js"></script>
    <script type="text/javascript" src="/rs-plugin/js/jquery.tp.min.js"></script>


</body>
</html>